### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by bburky** [naev/naev-website#2]
I noticed you moved the site and blog to a GitHub static site. May I please encourage you to add and RSS feed, even on a static site? It look like nanoc has an [`atom_feed()` helper](https://nanoc.ws/doc/reference/helpers/) that should do most of it for you.

I would also encourage you to find a way to send an HTTP redirect from the old http://blog.naev.org/feed/ URL to the new location. I was going through my RSS subscriptions in Feedly and noticed the Naev blog was dead/unreachable and went to check out what was going on.

**Comment by bobbens** [comment]
I have added the feed (https://naev.org/feed/). However, having the redirect does seem like something a bit trickier to do. I'll see what can be done.

**Comment by bburky** [comment]
Thanks for creating the new feed! The redirect is optional, but is nice if anyone hasn't updated their feed URL.

**Comment by bobbens** [comment]
OK, I'll close it then ;)

**Comment by doobilydo** [comment]
I'd like to recommend adding that link to the website somehow. I was trying to use the blarg url `https://naev.org/page/1/` because I didn't see another link.
