### ISSUE TITLE
Small list of TODOs

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev-website#4]
Just some line items to help with general quality of life stuff with maintenance and updates.

Generally important
- [x] Update the downloads page to point to github release links / stay up to date with them and a link to steam.
- [x] Automate the deployment of naev.org (solved by this PR https://github.com/naev/naev-website/pull/5)
- [x] Move api.naev.org to naev.org/api via some automated means (solved by this PR https://github.com/naev/naev-website/pull/5)

Not really that important
- [x] Merge ldocs css into naev.org stylesheet without breaking all the things

**Comment by bobbens** [comment]
The way I'm "deploying" is with `make install`. Should be possible to add to a github workflow no? It is doing cross-repo stuff though.

**Comment by ProjectSynchro** [comment]
@bobbens believe it or not there is a fancy way to do cross-repo stuff.
I have been investigating a little, and it seems like you can utilize the REST API to check for job statuses etc. realistically you should only need an API key with the right permissions for whatever repo you want to look at. (don't quote me on that though 😉)

**Comment by ProjectSynchro** [comment]
Looks like everything is done!
Congrats on the release!
next up is cleaning up those red x's on naev/naev.github.io
